### ISSUE TITLE
This is a suggestion not an issue :)

### ISSUE THREAD

**Issue by HiFiiDev** [thelearn-tech/Apache-configure#5]
So in my repos, I have a changelog script that generates a changelog and also have some various customizability. https://github.com/HiFiiDev/ROM-Changes

Would you like me to add a slimmed down version of a changelogger in your script? Like when the script first gets ran, add a prompt and ask the user if they'd like to see a changelog. If yes, run it (but keep it simple/quick), if not, move on and ask 

Perhaps the second time running the script, ask one more time, and if yes, ask if they'd like a changelog generated every launch.

Let me know it shouldn't be too hard

**Comment by thelearn-tech** [comment]
Plz discuss here
https://github.com/thelearn-tech/Apache-configure/discussions

**Comment by thelearn-tech** [comment]
So u want to promote user to see your changlog 
Script(like a small view of script and what it does)
If yes .and if no then it will continue with the script .

**Comment by HiFiiDev** [comment]
> So u want to promote user to see your changlog
> Script(like a small view of script and what it does)
> If yes .and if no then it will continue with the script .

It would not be to promote my script.  I would just add a block code in your script to add a changelog feature :)

I will probably just be using [this](https://github.com/HiFiiDev/BuildFenix/blob/master/changes.sh) for the starting point of the code, or I'll borrow from my changelog script.  There would be no self promotion
